### STAGE 1: Build ###
FROM node:12.18-alpine AS build
# ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
# npm ci include cache clean
RUN npm ci --only=production -silent
RUN npm i @angular/cli@10.1.6 -silent
# put ngcc in its own layer to avoid it being called on every ng build
RUN ./node_modules/.bin/ngcc
# RUN ./node_modules/.bin/ngcc --properties es2015 browser module main --create-ivy-entry-points
COPY . .
# DEFAULT configuration to production
ARG configuration=productionlocal
RUN npm run build -- --configuration $configuration

### STAGE 2: Run ###
FROM node:12.18-alpine
COPY --from=build /usr/src/app/dist/docker-angular-starter /usr/share/dist

