FROM node:12.18-alpine AS build
# ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
# npm ci include cache clean
RUN npm ci --only=production -silent
RUN npm i @angular/cli@10.1.6 -silent
# put ngcc in its own layer to avoid it being called on every ng build
RUN ./node_modules/.bin/ngcc
# RUN ./node_modules/.bin/ngcc --properties es2015 browser module main --create-ivy-entry-points
COPY . .
# DEFAULT configuration to production
ARG configuration=develop
RUN npm run build -- --configuration $configuration

# az acr login --name mcrbattlestar --expose-token
# docker login mcrbattlestar.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password the_exposed_token
# cid=$(docker create mcrbattlestar.azurecr.io/angular:angular_angular_master_20210316.4.binaries)
# docker cp $cid:/usr/src/app/dist/docker-angular-starter ./manifest


# cid=$(docker create dockerangularstarter:developlocal) 
# echo $cid
# docker cp $cid:/usr/src/app/dist/docker-angular-starter ./developlocal
