apiVersion: v1
kind: ConfigMap
metadata:
  name: envread-settings
  namespace: production
data:
  app.config.json: |-
    {
      "name": "envapp",
      "version": "1.0.0",
      "environment": "Production",
      "basehref": "envapp",
      "backgroundColor": "red"
    }

---    

apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      volumes:
      - name: envread-volume
        configMap:
          name: envread-settings    
      containers:
      - name: nginx
        image: mcr210225.azurecr.io/k8s/docker-angular-starter:ch1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        volumeMounts:
          - name: envread-volume
            mountPath: /usr/share/nginx/html/envapp/assets/

---

apiVersion: v1
kind: Service
metadata:
  name: angular
  namespace: production
spec:
  selector:
    app: angular
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
